/**
 * Name: Russell Tan
 * Date: 2/03/2015
 * Description: Project demonstrates the ability to connect to a database and retrieve values
 */

package lab2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Properties;

public class DerbyDemo1 
{	
	//Private members
	private static String connString = "jdbc:derby:/home/russell/squirrel-sql-3.6/Lab2;create=false";
	private static Connection conn = null;
	private static Statement statement = null;

	public static void main(String[] args)
	{
		connectToDB();
		SelectRecipes();
		shutdown();
	}
	
	/**
	 * Method to connect to database
	 */
	public static void connectToDB()
	{
		try
		{
			conn = DriverManager.getConnection(connString);			
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
		
	}
	
	/**
	 * Method that retrieves values stored in the db table
	 * Also displays them in a tabled format
	 */
	public static void SelectRecipes()
	{
		try
		{
			int k;
			String tableName = "recipes";
			//Create sql values
			statement = conn.createStatement();
			ResultSet results = statement.executeQuery("select * from "+tableName);
			ResultSetMetaData metaData = results.getMetaData();
			
			//Get the headers
			for(k = 0; k < metaData.getColumnCount(); k++)
			{
				System.out.print(metaData.getColumnLabel(k+1)+"\t\t");
			}
			//Separate the headers from the data
			System.out.println("\n____________________________________________________________");
			
			//Get values stored in table
			while(results.next())
			{
				int id = results.getInt(1);
				String recipeName = results.getString(2);
				System.out.println("|"+id + "\t\t\t|" + recipeName);
			}
			//Close all operations and connections
			results.close();
			statement.close();
			conn.close();
		}
		catch(SQLException e)
		{
			e.printStackTrace();
		}
	}
	
	/**
	 * Shutdown all connections just in case
	 */
	public static void shutdown()
	{
		try
		{
			if(statement != null)
			{
				statement.close();
			}
			
			if(conn != null)
			{
				DriverManager.getConnection(connString + ";shutdown=true");
				conn.close();
			}
		}
		//Empty catch block - otherwise errors are generated by default
		catch(SQLException e)
		{
			
		}
	}
}
